"""Build a printable meeting-packet markdown string from current planner metrics."""
from __future__ import annotations

from typing import Any, Dict, Optional


def build_packet_md(
    *,
    burn: float,
    return_pct: int,
    sleeve_total: float,
    non_muel_total: float,
    years_label: str,
    exhaust: Any,
    std_a: float,
    target_years: int,
    keep_brk: bool,
    distribute_m: float,
    fortress_pv_per_trust: Optional[float] = None,
    fortress_exhaust: Any = None,
    muel_mv: float = 0.0,
    muel_eai: float = 0.0,
) -> str:
    exhaust_s = "—" if exhaust is None else str(exhaust)
    ft_ex = "—" if fortress_exhaust is None else str(fortress_exhaust)
    ft_pv = "—" if fortress_pv_per_trust is None else f"${fortress_pv_per_trust:,.0f}"
    left_a = max(0.0, non_muel_total - std_a)
    short_a = max(0.0, std_a - non_muel_total)
    fortress_line = (
        f"Securities left for Fortress after Standard A: **${left_a/1e6:.1f}M**"
        if left_a > 0
        else f"Standard A needs **${short_a/1e6:.1f}M** more than today’s non-MUEL book"
    )
    return f"""# Family Land Trust planning packet

**Prepared for Investment Committee discussion** · Speculative planning estimates — not forecasts, legal, tax, or investment advice.

## 1. Snapshot

| Item | Value |
|------|------:|
| Non-MUEL book | ${non_muel_total/1e6:.1f}M |
| Settings · starting book | ${sleeve_total/1e6:.2f}M |
| Year-1 property costs | ${burn:,.0f} |
| Smooth stock return | {return_pct}% |
| Keep two BRK.A | {"Yes" if keep_brk else "No"} |
| Distribute now | ${distribute_m:.1f}M |
| Years of funding (smooth) | {years_label} |
| Exhaust year (smooth) | {exhaust_s} |

## 2. Reserve size — Standard A

Smallest reserve that funds land costs for **{target_years} years** at a smooth **{return_pct}%** return (same idea as Christopher’s IC memo).

- **Standard A keep:** ${std_a/1e6:.1f}M
- {fortress_line}

Standards B (Monte Carlo odds) and C (real-preserving) are available interactively on the planner’s Reserve size tab.

## 3. Fortress assessments (smooth path)

If the reserve runs out under current settings, draft planning treats later land costs as branch assessments.

- Exhaust year on this path: **{ft_ex}**
- Illustrative PV of bills per Fortress trust (through 2100 @ 5% discount): **{ft_pv}**

Confirm mechanics with the administrative trustee and trust counsel (draft Art. II ¶G).

## 4. MUEL (outside the non-MUEL reserve sleeve)

| Item | Value |
|------|------:|
| MUEL market value | ${muel_mv/1e6:.1f}M |
| MUEL dividend EAI | ${muel_eai:,.0f} |

## 5. Open decisions for the meeting

1. Cost basis: by-property vs Christopher’s figure vs IC $433k.
2. How much non-MUEL to keep vs distribute at decanting (Standard A vs full book).
3. Whether BRK.A stays in the Land Trust or is distributed to beneficiaries.
4. Whether Monte Carlo Standard B / realistic case should drive the “keep” number.
5. Assessment / sweep enforceability if Fortress trusts do not pay.

---
*Generated by Land Reserve Planner (Streamlit Phase 4). Re-run the app and toggle Meeting packet after changing settings to refresh.*
"""
